import {
    autoGeneratedHashKey,
    table,
    attribute
} from '@aws/dynamodb-data-mapper-annotations';

@table('readings')
export default class Reading {
    @autoGeneratedHashKey()
    id: string;
    @attribute()
    PM10: number;
    @attribute()
    PM25: number;
    @attribute()
    timestamp: Date;
    @attribute()
    location: string;
    @attribute()
    geo: Geolocation;

    public constructor(init?:Partial<Reading>) {
        Object.assign(this, init);
    }
}